import {useEffect, useState} from 'react';
import {fetchData} from '../utils/fetchData.js';

const MEDIA_API = import.meta.env.VITE_MEDIA_API + '/media';
const AUTH_API = import.meta.env.VITE_AUTH_API;
const UPLOAD_API = import.meta.env.VITE_UPLOAD_SERVER;

const useMedia = () => {
  // mediaArray state here
  const [mediaArray, setMediaArray] = useState([]);

  useEffect(() => {
    try {
      // Hae mediadata
      const getMedia = async () => {
        const mediaData = await fetchData(MEDIA_API);
        //console.log(mediaData);

        // Hae jokaiselle media-itemille käyttäjä
        const newArray = await Promise.all(
          mediaData.map(async (item) => {
            const user = await fetchData(`${AUTH_API}/users/${item.user_id}`);
            //console.log(user);
            return {...item, username: user.username};
          }),
        );

        console.log(newArray);
        setMediaArray(newArray);
      };

      getMedia();
    } catch (e) {
      console.log('Error;', e);
    }
  }, []);

  const postMedia = async (fileData, inputs, token) => {
    const fetchOptions = {
      method: 'POST',
      headers: {
        'Content-Type': 'application/json',
        Authorization: 'Bearer ' + token,
      },

      // create a suitable object for Media API: without media_id, user_id, thumbnail and created_at. All those are generated by the API. See the media API documentation.
      body: JSON.stringify({...inputs, ...fileData}),
    };

    // post the data to Media API and get the data as MediaResponse
    const mediaResponse = await fetchData(MEDIA_API, fetchOptions);

    // return the data
    return mediaResponse;
  };

  // Komponentille palautetaan mediaArray
  return {mediaArray, postMedia};
};

const useAuthentication = () => {
  const postLogin = async (inputs) => {
    const fetchOptions = {
      method: 'POST',
      headers: {
        'Content-Type': 'application/json',
      },
      body: JSON.stringify(inputs),
    };

    const loginResult = await fetchData(
      import.meta.env.VITE_AUTH_API + '/auth/login',
      fetchOptions,
    );
    return loginResult;
  };

  // useAuthenticationin return
  return {postLogin};
};

// Use user hook
const useUser = () => {
  const getUserByToken = async (token) => {
    const options = {
      headers: {
        Authorization: 'Bearer ' + token,
      },
    };

    const tokenResult = fetchData(`${AUTH_API}/token`, options);
    return tokenResult;
  };

  const postUser = async (user) => {
    // TODO: register new user here: http://media.mw.metropolia.fi/wbma/docs/#api-User-CreateUser
    console.log('postUser', user);
  };

  return {getUserByToken, postUser};
};

const useFile = () => {
  const postFile = async (file, token) => {
    // create FormData object
    const formData = new FormData();

    // add file to FormData
    formData.append('file', file); // include filename
    console.log('postFile formdata', formData);

    // upload the file to file server and get the file data (url = import.meta.env.VITE_UPLOAD_SERVER + '/upload')
    const options = {
      method: 'POST',
      headers: {
        Authorization: 'Bearer ' + token,
      },
      body: formData,
    };

    const uploadResponse = await fetchData(`${UPLOAD_API}/upload`, options);

    // TODO: return the file data.
    return uploadResponse;
  };

  return {postFile};
};

export {useMedia, useAuthentication, useUser, useFile};
